package com.putuwidiarsa.daftardino;

import java.util.ArrayList;

public class DinoData {
    public static String[][] data = new String[][]{
            {"Albertosaurus", "Albertosaurus adalah seekor dinosaurus pemakan daging yang besar, hidup pada akhir jaman Cretaceous. Walaupun ukurannya hanya separuh dari sepupu dekatnya yaitu Tyrannosaur, tapi sama-sama ganas", "9 Meter", "2.2 Ton", "1. Albertosaurus adalah anggota keluarga Tyrannosauridae yang artinya masih satu keluarga dengan tyrannosaur termasuk t-rex yang terkenal itu.\n2. Albertosaurus hidup akhir jaman Cretaceous kira-kira 70 juta tahun yang lalu.\n3.Albertosaurus berukuran hanya setengah dari tyrannosaur.\n4.Albertosaurus dinamai dari tempat pertama kali fosilnya ditemukan yaitu salah satu provinsi di Kanada.\n5. Fosil Albertosaurus kebanyakan ditemukan bergrup, ini menandakan bahwa Albertosaurus hidup dan berburu berkelompok.\n6. Albertosaurus memiliki tanduk kecil dibawah matanya. Ini mungkin berfungsi untuk menarik pasangan", "https://www.activewild.com/wp-content/uploads/2016/08/List-Of-Dinosaurs-Albertosaurus-1-768x512.jpg"},
            {"Allosaurus", "Allosaurus adalah dinosaurus karnivora (pemakan daging) berukuran besar. Ia hidup pada periode Jurassic / Cretaceous awal, sekitar 155 - 140 juta tahun yang lalu", "5 Meter/8 Meter", "4 Ton", "1. Allosaurus ditemukan di tempat yang sekarang adalah Benua Amerika\n2. Allosaurus berjalan dengan dua kaki\n3. Allosaurus memiliki sekitar 70 gigi runcing yang melengkung ke dalam\n4. Allosaurus lebih mengandalkan kukunya untuk mencabit dan memotong mangsanya, daripada menggigit dan mengunyah.", "https://www.activewild.com/wp-content/uploads/2016/08/allosaurus-768x512.jpg"},
            {"Ankylosaurus", "Ankylosaurus adalah anggota kelompok dinosaurus bernama Ankylosauria. Nama mereka berarti 'Kadal Lapis Baja' hal tersebut didasari bahwa tubuh dinosaurus ini terdiri atas lempengan cangkang keras yang tersusun.", "2 Meter/10 Meter", "7 Ton", "1. Dinosaurus paling berat jika dilihat dari rasio panjang dan tinggi badan\n2. Merupakan dinosaurus herbivora (Pemakan Tanaman).\n3. Tidak pernah gentar dalam menghadapi predator. Alih-alih melarikan diri, Ankylosaurus akan menghadapi segala jenis predator termasuk T-Rex\n4. Di ekornya terdapat jaringan menyerupai bola dari batu seberat 5 kg. Jika Ankylosaurus dihadang oleh lawannya, ia akan menyerang lawan tersebut dengan ekor kerasnya dan dalam sekejap lawannya akan terjatuh.", "https://www.activewild.com/wp-content/uploads/2016/08/dinosaur-names-and-pictures-ankylosaurus-768x512.jpg"},
            {"Apatosaurus", "Apatosaurus hidup sekitar 152 hingga 151 juta tahun yang lalu, di akhir Periode Jurassic. Apatosaurus termasuk golongan Sauropoda. Sauropoda adalah sekelompok dinosaurus yang termasuk beberapa hewan terbesar yang pernah hidup di bumi.", "5 Meter/23 Meter", "30 Ton", "1. Leher panjang Apatosaurus akan memungkinkannya mencapai dahan yang tinggi pada pohon untuk makanan. Apatosaurus mampu meningkatkan jangkauannya lebih jauh dengan mengangkat kaki belakangnya.\n2. Beratnya mencapai 36.000 kg (seberat 4 ekor gajah Afrika dewasa) dan dengan panjang hingga 28m, Apatosaurus adalah salah satu hewan terbesar yang pernah hidup di bumi.\n3. Ekornya yang panjang dan menyerupai cambuk, ternyata digunakan untuk keseimbangan daripada untuk senjata.\n4. Apatosaurus mampu hidup lebih dari 100 tahun.", "https://www.activewild.com/wp-content/uploads/2016/08/apatosaurus-768x512.jpg"},
            {"Archaeopteryx", "Archaeopteryx hidup pada zaman awal Tithonia dari zaman Jurassic Akhir, sekitar 150,8–148,5 juta tahun yang lalu. Penemuan Archaeopteryx pada awal tahun 1860-an adalah salah satu penemuan fosil terpenting sepanjang masa. Tidak hanya membuktikan adanya hubungan antara dinosaurus dan burung, tetapi juga mendukung teori evolusi yang dikemukakan dalam buku Darwin, 'On the Evolution of Species', yang telah diterbitkan hanya beberapa tahun sebelumnya.", "51 Cm", "1 Kg", "1. Penemuan fosil Archaeopteryx mampu membuktikan teori Darwin yang kontroversial yaitu evolusi dari dinosaurus menjadi burung modern.\n2. Fosil Archaeopteryx pertama yang ditemukan adalah sehelai bulu.\n3. Nama Archaeopteryx berasal dari kata Yunani untuk \'kuno\' dan \'sayap\' atau \'bulu\'.\n4. Archaeopteryx mungkin mampu terbang singkat dengan cara mengepakkan sayapnya namun tidak mampu melayang lama.", "https://www.activewild.com/wp-content/uploads/2016/08/Archaeopteryx-1-768x512.jpg"},
            {"Baryonyx", "Baryonyx adalah dinosaurus pemakan daging berukuran sedang yang berjalan dengan dua kaki. Meskipun tidak sepenuhnya akuatik, dinosaurus ini menghabiskan banyak waktu di atau dekat air. hal tersebut banyak mempengaruhi diet hewan ini yaitu pemburu ikan dan hewan air lainnya. Baryonyx hidup pada periode Cretaceous awal, sekitar 130 hingga 125 juta tahun yang lalu.", "10 Meter", "2 Ton", "1. Baryonyx adalah anggota keluarga Spinosauridae, dan memiliki hubungan dekat dengan Spinosaurus.\n2. Baryonyx adalah theropoda, sekelompok besar dinosaurus pemakan daging berkaki dua.\n3. Baryonyx memiliki leher lurus, tidak biasa di antara dinosaurus pemakan daging yang biasanya memiliki leher berbentuk huruf S.\n4. Banyak ditemukan fosil sisik ikan pada fosil Baryonyx bagian perut menandakan sebagian besar diet dinosaurus ini adalah ikan.", "https://www.activewild.com/wp-content/uploads/2016/08/baryonyx_walkeri_restoration-768x267.jpg"},
            {"Brachiosaurus", "Dibandingkan dengan sauropoda lainnya, Brachiosaurus memiliki ekor yang pendek. Ketebalannya memberikan keseimbangan bagi ujung depan dinosaurus yang paling berat. Brachiosaurus memiliki otak kecil dan sangat mungkin untuk memiliki kecerdasan rendah.", "12 Meter/25 Meter", "60 Ton", "1. Sebagai ilustrasi berat Brachiosaurus adalah seberat 30 mobil minibus dan panjangnya sepanjang 3 bis yang diparkir paralel\n2. Seorang pria dewasa bisa dengan mudah berjalan di bawah Brachiosaurus yang berdiri tanpa membenturkan kepalanya.\n3. Brachiosaurus dewasa tidak memiliki predator karena ukurannya yang besar. Namun, Brachiosaurus muda akan menjadi target karnivora besar yang ada pada saat itu, seperti Allosaurus.\n4. Brachiosaurus menjelajahi bumi selama periode Jurassic pertengahan hingga akhir, sekitar 155,5 hingga 150,8 juta tahun yang lalu.", "https://www.activewild.com/wp-content/uploads/2016/08/Brachiosaurus-2-768x512.jpg"},
            {"Carnotaurus", "Carnotaurus adalah dinosaurus theropoda ukuran sedang. Ia hidup di tempat yang sekarang disebut Amerika Selatan pada akhir Zaman Cretaceous, sekitar 72 hingga 69,9 juta tahun yang lalu. Carnotaurus memiliki tanduk dan rahang atas yang sangat kuat.", "9 Meter", "2 Ton", "1. Carnotaurus adalah satu-satunya dinosaurus pemakan daging yang kita tahu memiliki tanduk.\n2. Carnotaurus merupakan dinosaurus karnivora besar yang cepat, ia memiliki kaki yang panjang dan kuat, yang menurut para ilmuwan mungkin memungkinkannya mencapai kecepatan hingga 56 km/jam.\n3. Carnotaurus memiliki lengan lebih pendek daripada dinosaurus pemakan daging besar lainnya. Ya, lengannya bahkan lebih pendek dari T Rex yang terkenal itu.\n4. Semua yang kita ketahui tentang Carnotaurus berasal dari satu kerangka, yang ditemukan pada tahun 1984 oleh ahli paleontologi José Bonaparte.", "https://www.activewild.com/wp-content/uploads/2016/08/Carnotaurus-1-768x512.jpg"},
            {"Deinonychus", "", "3 Meter", "80 Kg", "1. Deinonychus adalah bahasa Yunani untuk \'Cakar yang Mengerikan\'\n2. Deinonychus Menginspirasi Teori bahwa Burung Berasal dari Dinosaurus.\n3. Deinonychus hampir seluruh tubuhnya ditutupi dengan Bulu\n4. Deinonychus menggunakan cakar belakangnya untuk membedah perut mangsanya\n5. Deinonychus adalah model untuk Velociraptors pada film Jurassic Park", "https://www.activewild.com/wp-content/uploads/2016/08/list-of-dinosaurs-deinonychus-768x512.jpg"},
            {"Compsognathus", "Compsognathus yang dalam bahasa Yunani berarti elegan, halus, mungil adalah genus dinosaurus theropoda kecil, bipedal, karnivora. Mereka hidup sekitar 150 juta tahun yang lalu, selama zaman Tithonia dari akhir periode Jurassic", "1 Meter", "3 Kg", "1. Compsognathus adalah hewan bipedal kecil dengan kaki belakang yang panjang dan ekor yang lebih panjang. Ekor yang panjang ini mereka gunakan untuk menjaga keseimbangan selama pergerakan terutama pada saat berburu\n2. Compsognathus bisa tumbuh hingga seukuran kalkun\n3. Compsognathus termasuk kedalam genus dinosaurus pertama yang digambarkan memiliki bulu", "https://www.activewild.com/wp-content/uploads/2018/12/Compsognathus-768x380.jpg"}
    };

    public static ArrayList<Dino> getListData(){
        ArrayList<Dino> list = new ArrayList<>();
        for (String[] aData : data) {
            Dino dino = new Dino();
            dino.setName(aData[0]);
            dino.setDescription(aData[1]);
            dino.setHeight(aData[2]);
            dino.setWeight(aData[3]);
            dino.setFacts(aData[4]);
            dino.setImg(aData[5]);
            list.add(dino);
        }
        return list;
    }
}
